"""
research/data/provenance.py
===========================
Source classes for bar data and the rule that decides which of them strategy code may see
(plan rule 1.2.11; Antigravity/Yashu 2026-09-25: Yahoo data is QA_ONLY).

Every parquet file written by research/data/ingest_json.py carries a `source` column with one of the
classes below. ParquetCandleStore refuses, in STRATEGY mode, any file whose class is not in
STRATEGY_SOURCES; such data can be opened only with mode="QA", which the engine and PointInTimeView
refuse in turn. So QA_ONLY data can be validated and cross-checked but never reaches a strategy.

Classes
- DHAN_API_V2       Dhan v2 charts API (the plan's approved intraday source). Strategy-eligible.
- SYNTHETIC         generated by tests. Strategy-eligible (it is never mistaken for market data).
- YAHOO_CHART_V8    Yahoo Finance public chart API. QA_ONLY: 60-day 15m cap, and the 09:15 bar omits the
                    pre-open auction (measured against Kite, Claude outputs/2026-09-25_p3_hold_data_audit.md).
- KITE_WEB_SESSION  the 32-session file from kite.zerodha.com/oms (plan rule 1.2.11: never refreshed; kept
                    as the P2 regression reference). QA_ONLY in the parquet layer.
- UPSTOX_API_V2     Upstox V2 historical-candle API (broker's official endpoint, research/data/upstox_history.py;
                    Yashu 25 Sep 2026). QA_ONLY until it passes the P3.9 Kite cross-check; then Yashu's
                    instruction makes it strategy-eligible.
- HF_UPSTOX_MIRROR  third-party Hugging Face mirror of Upstox 1-minute data (proposed by Antigravity for P7).
                    QA_ONLY until Yashu approves it as a source and it passes the P3.9 cross-source check.
- UNKNOWN           anything unlabelled. QA_ONLY (fail closed).
"""
from __future__ import annotations

from typing import Any, Mapping

DHAN = "DHAN_API_V2"
SYNTHETIC = "SYNTHETIC"
YAHOO = "YAHOO_CHART_V8"
KITE = "KITE_WEB_SESSION"
UPSTOX = "UPSTOX_API_V2"
HF_UPSTOX = "HF_UPSTOX_MIRROR"
UNKNOWN = "UNKNOWN"

STRATEGY_SOURCES = frozenset({DHAN, SYNTHETIC})
ALL_SOURCES = frozenset({DHAN, SYNTHETIC, YAHOO, KITE, UPSTOX, HF_UPSTOX, UNKNOWN})


class SourceNotAllowedError(PermissionError):
    """Raised when a STRATEGY-mode store is asked to serve data from a QA_ONLY source."""


def classify(entry: Mapping[str, Any]) -> str:
    """Source class of one symbol entry of the canonical candle JSON."""
    src = str(entry.get("source") or "").strip()
    url = str(entry.get("source_url") or "").lower()
    up = src.upper()
    if up in ALL_SOURCES:
        return up
    if src.startswith("YahooFinance_") or "finance.yahoo.com" in url:
        return YAHOO
    if "kite.zerodha.com" in url or up.startswith("KITE"):
        return KITE
    if up.startswith("DHAN") or "api.dhan.co" in url:
        return DHAN
    if "api.upstox.com" in url and "huggingface.co" not in url:
        return UPSTOX
    if "UPSTOX" in up or "huggingface.co" in url:
        return HF_UPSTOX
    return UNKNOWN


def strategy_eligible(source_class: str) -> bool:
    return source_class in STRATEGY_SOURCES
